require:
  - rubocop-capybara
  - rubocop-factory_bot
  - rubocop-graphql
  - rubocop-rails
  - rubocop-rspec

AllCops:
  TargetRubyVersion: 3.2.2
  NewCops: enable
  Exclude:
    - config/environments/*
    - db/schema.rb
    - bin/**/*
    - tmp/**/*
    - vendor/**/*
    - node_modules/**/*
    - spec/spec_helper.rb

GraphQL/ArgumentDescription:
  Enabled: false

GraphQL/FieldDescription:
  Enabled: false

GraphQL/ObjectDescription:
  Enabled: false

GraphQL/MaxDepthSchema:
  Enabled: false

GraphQL/MaxComplexitySchema:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/StringLiterals:
  EnforcedStyle: double_quotes

Layout/ParameterAlignment:
  EnforcedStyle: with_fixed_indentation

Layout/MultilineMethodCallIndentation:
  EnforcedStyle: indented

Style/TrailingCommaInArrayLiteral:
  EnforcedStyleForMultiline: consistent_comma

Style/TrailingCommaInHashLiteral:
  EnforcedStyleForMultiline: consistent_comma

Rails/SkipsModelValidations:
  Enabled: false
